### PR TITLE
Allow use in app extensions

### PR DESCRIPTION
**Pull request by klaaspieter**
Waiting for behrang/YamlSwift#45 and drmohundro/SWXMLHash#106 to be merged and released.

### CODE REVIEW

**Comment by klaaspieter** [comment]
Instead of waiting for the frameworks to be released we could point Carthage at the branches on my forks temporarily.

I'm also [still wondering][] if this allows users to use non-extension-safe APIs.

[still wondering]: https://github.com/jpsim/SourceKitten/issues/299#issuecomment-261251996

**Comment by jpsim** [comment]
> I'm also still wondering if this allows users to use non-extension-safe APIs.

It's not that the APIs aren't extension safe, it's that SourceKitten opens an XPC connection to `sourcekitd.framework` with any codepath that goes through `Request.send()` basically.

**Comment by klaaspieter** [comment]
Can we prevent that somehow? Should it be documented somewhere?

**Comment by klaaspieter** [comment]
The last two commits should be everything that was left to do for this to work.

**Comment by jpsim** [comment]
> Can we prevent that somehow? Should it be documented somewhere?

Don't know, and probably. This would need a bit more research. Maybe @norio-nomura has some ideas here since he's actually used SourceKitten in an Xcode Source Editor Extension already. I haven't, so I'm not super familiar.

**Comment by jpsim** [comment]
Looks great, thanks!

**Pull request merged**
