### PR TITLE
Support building with Swift 4.1

### PR DESCRIPTION
**Pull request by norio-nomura**
- depends on https://github.com/jpsim/Yams/pull/98

### CODE REVIEW

**Comment by norio-nomura** [comment]
`OffsetMapTests.testOffsetMapContainsDeclarationOffsetWithDocCommentButNotAlreadyDocumented()` is failing because SourceKit on Swift 4.1 returns information about `subscript(_:)`([SR-5035](https://bugs.swift.org/browse/SR-5035)).
https://gist.github.com/norio-nomura/2705070b46378dc7cbb932a046a31881/revisions
@jpsim How should we fix this?

**Comment by norio-nomura** [comment]
> How should we fix this?

Changed expected result in `OffsetMapTests.testOffsetMapContainsDeclarationOffsetWithDocCommentButNotAlreadyDocumented()`.

**Comment by norio-nomura** [comment]
Marked as WIP again, since this still depends on `master` branch of Yams.

**Comment by jpsim** [comment]
Any reason not to cut a release of Yams?

**Comment by norio-nomura** [comment]
I was thinking about refactoring Yams, but I canceled it for the time being, so there is no particular reason right now.

**Comment by jpsim** [comment]
Yams 0.6.0 has been cut. I've updated this PR and will merge when CI passes. Thanks!

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
