### PR TITLE
Use StringView instead of excessive caching in NSString

### PR DESCRIPTION
**Pull request by PaulTaykalo**
- Removing cache from NSstring
- The cache was replaced by StringView property

### CODE REVIEW

**Comment by PaulTaykalo** [comment]
@jpsim access to byte <-> NSrange without the caching and locks inside of strings.
So, basically, if someone needs to cache the results, the caller is responsible for doing so.

**Comment by PaulTaykalo** [comment]
@jpsim bump

**Comment by jpsim** [comment]
Sorry for the delay, I'm finally looking at this. Have you run preliminary numbers of SwiftLint or other projects that depend on SourceKitten (e.g. jazzy) to see how this affects their performance?

> if someone needs to cache the results, the caller is responsible for doing so.

Do you have an example of what this looks like? How involved is it? For a tool like jazzy, which uses SourceKitten as a CLI executable, it doesn't cache anything, it relies entirely on a single invocation of SourceKitten to generate the documentation data.

---

If we can keep the runtime of jazzy & SwiftLint similar or better to what it was with this excessive caching, I'm very much in favor of removing that caching altogether.

**Comment by jpsim** [comment]
> Do you have an example of what this looks like?

I just found https://github.com/realm/SwiftLint/pull/2964. I'll be looking at that for details.

**Comment by jpsim** [comment]
The impact to jazzy's use case seems unaffected 🕺 

```
$ hyperfine './sourcekitten-master doc --spm-module Yams' './sourcekitten-stringview doc --spm-module Yams' 
Benchmark #1: ./sourcekitten-master doc --spm-module Yams
  Time (mean ± σ):     14.374 s ±  0.691 s    [User: 599.9 ms, System: 120.1 ms]
  Range (min … max):   13.714 s … 15.984 s    10 runs
 
Benchmark #2: ./sourcekitten-stringview doc --spm-module Yams
  Time (mean ± σ):     14.783 s ±  0.651 s    [User: 609.7 ms, System: 116.3 ms]
  Range (min … max):   13.850 s … 15.739 s    10 runs
 
Summary
  './sourcekitten-master doc --spm-module Yams' ran
    1.03 ± 0.07 times faster than './sourcekitten-stringview doc --spm-module Yams'
```

**Pull request merged**
