### PR TITLE
Improve swift doc comment association

### PR DESCRIPTION
**Pull request by johnfairh**
This PR reworks how swift doc comments are associated with declarations: it waits until all the declarations have been found then passes over the file once matching comments to declarations.  This solves #368 and also restores doc comments lost due to #269.

The first commit deals with some bugs causing declarations found in `processFurther()` not to be correctly ordered.  The second commit has the doc comment changes -- the docs shown disappearing from the test fixtures should not have been there.

### CODE REVIEW

**Comment by johnfairh** [comment]
Oops didn't read instructions properly ... will add swift 3.0 support ...

**Comment by jpsim** [comment]
Thanks for working on this! I could use your help in reviewing the effect this has on jazzy's integration specs: https://github.com/realm/jazzy-integration-specs/commit/275ea07ccc730efe5474e2cdbba22fd55a4291c9

I've confirmed that the changes to Alamofire & Moya are all good, but I'd like your help to analyze the changes to Realm Swift & Siesta if possible:

**Alamofire**

- [x] `s:C9Alamofire11DataRequest10Validation` moved from top-level to nested in `DataRequest`
- [x] `s:C9Alamofire15DownloadRequest10Validation` moved from top-level to nested in `DownloadRequest`
- [x] `s:C9Alamofire15DownloadRequest23DownloadFileDestination` was reordered to match its location in the source file
- [x] `s:OC9Alamofire26NetworkReachabilityManager14ConnectionType` was reordered to match its location in the source file
- [x] `s:iC9Alamofire15SessionDelegate9subscriptFCSo14URLSessionTaskGSqCS_7Request_` was reordered to match its location in the source file
- [x] `s:P9Alamofire30DataResponseSerializerProtocol16SerializedObject` was reordered to match its location in the source file
- [x] `s:vP9Alamofire34DownloadResponseSerializerProtocol17serializeResponseFTGSqV10Foundation10URLRequest_GSqCSo15HTTPURLResponse_GSqVS1_3URL_GSqPs5Error___GOS_6Resultwx16SerializedObject_` was reordered to match its location in the source file
- [x] `s:V9Alamofire22DataResponseSerializer16SerializedObject` was reordered to match its location in the source file
- [x] `s:V9Alamofire26DownloadResponseSerializer16SerializedObject` was reordered to match its location in the source file

**Moya**

- [x] Several previously incorrectly resolved doc comments were dropped from undocumented members
- [x] Several previously missing doc comments were added to documented members in extensions
- [x] A handful of declarations were reordered to match their location in the source file

**Realm Swift & Siesta**

Lots of changes here that I haven't reviewed yet.

**Comment by jpsim** [comment]
Thank you so much for taking the time to review those. I have a few suggestions, mostly lowering the ACLs for the new declarations you've added since I don't think they should be exposed in SourceKittenFramework's public API, and some very small refactors, could you please take a look at if you're okay with them, I'll apply them to your branch:

```diff
commit 5e06457fce3eb5977cf98f5b5cf7547b3791f0cf
Author: JP Simard <jp@jpsim.com>
Date:   Tue May 9 10:13:22 2017 -0700

    mostly downgrade newly added APIs from public to internal

diff --git a/Source/SourceKittenFramework/File.swift b/Source/SourceKittenFramework/File.swift
index 17c96ac..6f28b7d 100644
--- a/Source/SourceKittenFramework/File.swift
+++ b/Source/SourceKittenFramework/File.swift
@@ -282,8 +282,7 @@ public final class File {
     */
     private func shouldInsert(parent: [String: SourceKitRepresentable], offset: Int64) -> Bool {
         return SwiftDocKey.getSubstructure(parent) != nil &&
-            ((offset == 0) ||
-            SwiftDocKey.getNameOffset(parent) == offset)
+            ((offset == 0) || SwiftDocKey.getNameOffset(parent) == offset)
     }
 
     /**
@@ -313,14 +312,15 @@ public final class File {
             return parent
         }
         for key in parent.keys {
-            if let subArray = parent[key] as? [SourceKitRepresentable] {
-                var subArray = subArray
-                for i in 0..<subArray.count {
-                    if let subDict = insert(doc: doc, parent: subArray[i] as! [String: SourceKitRepresentable], offset: offset) {
-                        subArray[i] = subDict
-                        parent[key] = subArray
-                        return parent
-                    }
+            guard var subArray = parent[key] as? [SourceKitRepresentable] else {
+                continue
+            }
+            for i in 0..<subArray.count {
+                let subDict = insert(doc: doc, parent: subArray[i] as! [String: SourceKitRepresentable], offset: offset)
+                if let subDict = subDict {
+                    subArray[i] = subDict
+                    parent[key] = subArray
+                    return parent
                 }
             }
         }
@@ -359,7 +359,7 @@ public final class File {
     - parameter syntaxMap: syntaxmap for the file
     - returns: dictionary of declarations with comments
     */
-    public func addDocComments(dictionary: [String: SourceKitRepresentable], syntaxMap: SyntaxMap) -> [String: SourceKitRepresentable] {
+    internal func addDocComments(dictionary: [String: SourceKitRepresentable], syntaxMap: SyntaxMap) -> [String: SourceKitRepresentable] {
         return addDocComments(dictionary: dictionary, finder: syntaxMap.createDocCommentFinder())
     }
 
@@ -369,12 +369,12 @@ public final class File {
      - parameter finder: current state of doc comment location
      - returns: updated version of declaration dictionary
      */
-    func addDocComments(dictionary: [String: SourceKitRepresentable], finder: SyntaxMap.DocCommentFinder) -> [String: SourceKitRepresentable] {
+    internal func addDocComments(dictionary: [String: SourceKitRepresentable], finder: SyntaxMap.DocCommentFinder) -> [String: SourceKitRepresentable] {
         var dictionary = dictionary
 
         // special-case skip 'enumcase': has same offset as child 'enumelement'
-        if let kind = SwiftDocKey.getKind(dictionary),
-           kind != SwiftDeclarationKind.enumcase.rawValue,
+        if let kind = SwiftDocKey.getKind(dictionary).flatMap(SwiftDeclarationKind.init),
+           kind != .enumcase,
            let offset = SwiftDocKey.getBestOffset(dictionary),
            let commentRange = finder.getRangeForDeclaration(atOffset: Int(offset)),
            case let start = commentRange.lowerBound,
@@ -386,7 +386,7 @@ public final class File {
 
         if let substructure = SwiftDocKey.getSubstructure(dictionary) {
             dictionary[SwiftDocKey.substructure.rawValue] = substructure.map {
-                self.addDocComments(dictionary: $0 as! [String: SourceKitRepresentable], finder: finder)
+                addDocComments(dictionary: $0 as! [String: SourceKitRepresentable], finder: finder)
             }
         }
 
diff --git a/Source/SourceKittenFramework/SyntaxMap.swift b/Source/SourceKittenFramework/SyntaxMap.swift
index a8361e8..05e0ab1 100644
--- a/Source/SourceKittenFramework/SyntaxMap.swift
+++ b/Source/SourceKittenFramework/SyntaxMap.swift
@@ -57,8 +57,8 @@ public struct SyntaxMap {
 
 extension SyntaxToken {
     /// Is this a doc comment?
-    public var isDocComment: Bool {
-        return SyntaxKind.docComments().map { $0.rawValue }.contains(type)
+    internal var isDocComment: Bool {
+        return SyntaxKind.docComments().contains { $0.rawValue == type }
     }
 }
 
@@ -77,7 +77,7 @@ extension Array {
 extension SyntaxMap {
     /// The ranges of documentation comments described by the map, in the order
     /// that they occur in the file.
-    public var docCommentRanges: [Range<Int>] {
+    internal var docCommentRanges: [Range<Int>] {
         let docCommentBlocks = tokens.split { !$0.isDocComment }
         return docCommentBlocks.flatMap { ranges in
             ranges.first.flatMap { first in
@@ -94,20 +94,20 @@ extension SyntaxMap {
     The `getRangeForDeclaration(atOffset:)` method should be called with the file's
     declaration offsets in order to retrieve the most appropriate doc comment for each.
     */
-    public final class DocCommentFinder {
+    internal final class DocCommentFinder {
         /// Remaining doc comments that have not been assigned or skipped
         private var ranges: [Range<Int>]
         /// The most recent file offset requested
         private var previousOffset: Int
 
         /// Create a new doc comment finder from a `SyntaxMap`.
-        public init(syntaxMap: SyntaxMap) {
+        internal init(syntaxMap: SyntaxMap) {
             self.ranges = syntaxMap.docCommentRanges
             self.previousOffset = -1
         }
 
         /// Get the byte range of the declaration's doc comment, or nil if none.
-        public func getRangeForDeclaration(atOffset offset: Int) -> Range<Int>? {
+        internal func getRangeForDeclaration(atOffset offset: Int) -> Range<Int>? {
             guard offset > previousOffset else { return nil }
 
             let commentsBeforeDecl = ranges.prefix { $0.upperBound < offset }
@@ -118,7 +118,7 @@ extension SyntaxMap {
     }
 
     /// Create a new doc comment finder for this map
-    public func createDocCommentFinder() -> DocCommentFinder {
+    internal func createDocCommentFinder() -> DocCommentFinder {
         return DocCommentFinder(syntaxMap: self)
     }
 }
```

**Comment by johnfairh** [comment]
No problem - glad you did half.  Those changes all look good to me; will add you to my fork in case you plan to do it that way.

**Comment by jpsim** [comment]
Awesome work.

**Comment by jpsim** [comment]
FYI: 9ba289c

**Pull request merged**
