### PR TITLE
Fix build errors with Xcode 13 beta

### PR DESCRIPTION
**Pull request by thii**

### CODE REVIEW

**Comment by thii** [comment]
@jpsim Can you review?

**Comment by DesmanLead** [comment]
+1 for reviewing this, this is the only thing that breaks our build on Xcode 13.

**Comment by PaulTaykalo** [comment]
It Seems that the `master` branch is working fine in Xcode 13 beta 4.
What's the usecase? How are you trying to compile Sourcekitten?

**Comment by johnfairh** [comment]
It was broken in earlier betas, some Swift 5.5 regression that's fixed in latest.

**Comment by PaulTaykalo** [comment]
Will close then PR then. leave a comment if it's still a thing

**Pull request closed without merging**
