### PR TITLE
[travis] Add Xcode 9 jobs

### PR DESCRIPTION
**Pull request by norio-nomura**
Added jobs will fail with https://bugs.swift.org/browse/SR-5288

### CODE REVIEW

**Comment by jpsim** [comment]
Xcode 9 beta 3 should fix this. I've filed https://github.com/travis-ci/travis-ci/issues/8070 to track when Travis makes that version available.

**Comment by jpsim** [comment]
Now depends on #402.

**Comment by jpsim** [comment]
Thanks!

**Comment by norio-nomura** [comment]
😊

**Pull request merged**
