### PR TITLE
Inherit custom toolchains while building Xcode

### PR DESCRIPTION
**Pull request by zwaldowski**
Analogous to #150, but for hacking on SourceKitten under Xcode.

Builds and runs in Xcode 6.2 and 6.3, but currently the tests only succeed under 6.2 with any Swift prior to 2016-01-25. Later builds of Swift 2.2 have the new `associatedtype` token and Xcode 6.3 causes changes to the autocomplete output that are valid (better, even) but don't pass the tests.

### CODE REVIEW

**Comment by norio-nomura** [comment]
`FRAMEWORK_SEARCH_PATHS` is used on linking. But not for dynamic loading on process launch.
It needs modifying `LD_RUNPATH_SEARCH_PATHS`.
https://github.com/jpsim/SourceKitten/pull/110 would be help.

How to know which library is loaded:
```sh
% DEVELOPER_DIR="/Applications/Xcode-beta.app" TOOLCHAINS=swift make install
…
2016-01-31 09:47:57.677 xcodebuild[53883:1371777] Build settings from command line:
2016-01-31 09:47:57.677 xcodebuild[53883:1371777]     ENABLE_BITCODE = NO
2016-01-31 09:47:57.677 xcodebuild[53883:1371777]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
2016-01-31 09:47:57.677 xcodebuild[53883:1371777]     SWIFT_LINK_OBJC_RUNTIME = YES
2016-01-31 09:47:57.677 xcodebuild[53883:1371777]     TOOLCHAINS = org.swift.20160125a
2016-01-31 09:47:57.677 xcodebuild[53883:1371777]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-01-25-a.xctoolchain
…
installer: The upgrade was successful.
% lldb /usr/local/bin/sourcekitten
(lldb) target create "/usr/local/bin/sourcekitten"
Current executable set to '/usr/local/bin/sourcekitten' (x86_64).
(lldb) image list
[  0] 658E982D-B26C-3545-9EF9-1E437E8E1C97 0x0000000100000000 /usr/local/bin/sourcekitten 
…
[ 66] 9F8FC39A-9E5F-374C-A497-FE729ED23EA5 0x0000000000000000 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/sourcekitd 
[ 67] 426A91A9-8E70-3FC4-A81D-F42B0B489731 0x0000000000000000 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib 
```

**Comment by zwaldowski** [comment]
Thanks! I forgot to pull that in from my previous branch.

I don't think setting `LD_RUNPATH_SEARCH_PATHS` is a long-term solution for having multiple toolchains on the system; [xcinvoke](https://github.com/segiddins/xcinvoke) should be elided into the framework in order to load a weakly-linked SourceKit.

**Comment by norio-nomura** [comment]
Don't include `$(inherited)` into `LD_RUNPATH_SEARCH_PATHS`. Because xcconfig's `LD_RUNPATH_SEARCH_PATHS` is wrong and caused trouble that I fixed on #110.

**Comment by norio-nomura** [comment]
Thanks.

Now, library loading seems good. :+1:  
Xcode 7.3 beta (7D129n) with swift-2.2-SNAPSHOT-2016-01-25-a:
```sh
% DEVELOPER_DIR="/Applications/Xcode-beta.app" TOOLCHAINS=swift make install
…
% lldb /usr/local/bin/sourcekitten
(lldb) target create "/usr/local/bin/sourcekitten"
Current executable set to '/usr/local/bin/sourcekitten' (x86_64).
(lldb) image list
…
[ 66] 82A92B4A-8762-32A4-B8A7-33C66A045C1E 0x0000000000000000 /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-01-25-a.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/sourcekitd 
      /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-01-25-a.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/sourcekitd.dSYM/Contents/Resources/DWARF/sourcekitd
[ 67] 386EE4CC-6955-3834-8231-345C48E862E3 0x0000000000000000 /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-01-25-a.xctoolchain/usr/lib/libclang.dylib 
      /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2016-01-25-a.xctoolchain/usr/lib/libclang.dylib.dSYM/Contents/Resources/DWARF/libclang.dylib
```
Xcode 7.3 beta (7D129n):
```sh
% DEVELOPER_DIR="/Applications/Xcode-beta.app" make install
…
% lldb /usr/local/bin/sourcekitten
(lldb) target create "/usr/local/bin/sourcekitten"
Current executable set to '/usr/local/bin/sourcekitten' (x86_64).
(lldb) image list
…
[ 66] 9F8FC39A-9E5F-374C-A497-FE729ED23EA5 0x0000000000000000 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/sourcekitd 
[ 67] 426A91A9-8E70-3FC4-A81D-F42B0B489731 0x0000000000000000 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib 
```
Xcode 7.2 (7C68):
```sh
% make install
…
% lldb /usr/local/bin/sourcekitten
(lldb) target create "/usr/local/bin/sourcekitten"
Current executable set to '/usr/local/bin/sourcekitten' (x86_64).
(lldb) image list
…
[ 66] 6313D92E-350D-336D-8FCD-531BB26DF35F 0x0000000000000000 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/sourcekitd 
[ 67] 59377044-CF9C-37B4-803F-6F7DE7A20DB5 0x0000000000000000 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib 
```

  
But, test is failing on both of Xcode 7.3 beta (7D129n). :cry: 

Xcode 7.3 beta (7D129n) with swift-2.2-SNAPSHOT-2016-01-25-a:
```sh
% DEVELOPER_DIR="/Applications/Xcode-beta.app" TOOLCHAINS=swift make test
…
Test Suite 'All tests' failed at 2016-01-31 13:36:08.863.
	 Executed 38 tests, with 6 failures (0 unexpected) in 28.899 (28.932) seconds
** TEST FAILED **
```
Xcode 7.3 beta (7D129n):
```sh
% DEVELOPER_DIR="/Applications/Xcode-beta.app" make test
…
Test Suite 'All tests' failed at 2016-01-31 13:33:39.606.
	 Executed 38 tests, with 5 failures (0 unexpected) in 28.366 (28.396) seconds
** TEST FAILED **
```

Can we make test pass on both of Xcode 7.2 and 7.3?

**Comment by zwaldowski** [comment]
Most of the failures are related to changes to code completion, but I'm not sure what the differences are.

The extra failure when running under 6.3 with a custom toolchain is for ObjC important; the Swift Open Source Toolchains don't include a full libc. I'll investigate that, at least.

**Comment by jpsim** [comment]
This is great, @zwaldowski! Could you add a matrix entry to `.travis.yml` so we can also test this configuration on CI?

**Comment by zwaldowski** [comment]
Sure! That might get complicated quickly given the changes to the toolchains (the 6.3 stuff mentioned above, new language additions like `associatedtype`) but I'll look into it shortly.

**Comment by jpsim** [comment]
> Sure! That might get complicated quickly given the changes to the toolchains (the 6.3 stuff mentioned above, new language additions like associatedtype) but I'll look into it shortly.

Ok thanks! We're already testing this stuff for the SPM build, so we'll already be doing this maintenance work anyway, so there should hopefully just be a one-time setup cost to making this testable on CI.

**Comment by jpsim** [comment]
@zwaldowski are you still working on this? From what I can tell, all these changes could be merged as-is, the only issue being the test failures with Xcode 7.3 beta, which would occur even without this patch anyway.

**Comment by zwaldowski** [comment]
Just need to do the Travis change, which I was going to this evening!

**Comment by jpsim** [comment]
Excellent! Thanks

**Comment by zwaldowski** [comment]
Merged with master. @norio-nomura, please check that the changes `LD_RUNPATH_SEARCH_PATHS` are correct with respect to 524306a.

@jpsim: Travis now executes `xcodebuild build` for Xcode-with-toolchain. This will be a little fiddly until 7.3, but it does the job for now. Cheers!

**Comment by norio-nomura** [comment]
By `make install` and `make prefix_install PREFIX=/usr/local`, `LC_RPATH` are following:
```sh
% otool -l /usr/local/Frameworks/SourceKittenFramework.framework/SourceKittenFramework
…
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
Load command 24
          cmd LC_RPATH
      cmdsize 24
         path /usr/lib (offset 12)
Load command 25
          cmd LC_RPATH
      cmdsize 104
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib (offset 12)
Load command 26
          cmd LC_RPATH
      cmdsize 104
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib (offset 12)
Load command 27
          cmd LC_RPATH
      cmdsize 104
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib (offset 12)
Load command 28
          cmd LC_RPATH
      cmdsize 104
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib (offset 12)
Load command 29
          cmd LC_RPATH
      cmdsize 104
         path /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib (offset 12)
```
It would be better `LD_RUNPATH_SEARCH_PATHS` is unchanged on .pkg (`make package`) and Homebrew (`make prefix_install`).
Can we apply changes to `LD_RUNPATH_SEARCH_PATHS` only on `make with_toolchain`?

**Comment by norio-nomura** [comment]
> Can we apply changes to LD_RUNPATH_SEARCH_PATHS only on make with_toolchain?

Oh, I didn't think about debugging on Xcode 7.3 with Open Source Toolchains…

Should we clear what purpose we runs each building processes for?

**Comment by jpsim** [comment]
I'll admit that this stuff is a weakness of mine, I don't understand much. I certainly like where this is going, but I'll defer to @norio-nomura to figure out what remains to be done.

**Comment by zwaldowski** [comment]
I do not think that anything that could be done using Xcode should be required to be applied as an `xcconfig` change using `make`.

We could potentially get rid of `DT_TOOLCHAIN_DIR` or `TOOLCHAIN_DIR`, one is a duplicate of the other for legacy reasons. I don't think the manual `/Applications/` versions are necessary with the other three resolved versions, but I'll defer to @norio-nomura on that.

Having a complex `LD_RUNPATH_SEARCH_PATHS` is a necessary evil, for now; I think the long-term solution is to find the toolchain at runtime rather than link-time, which I was working on in another branch. That'll require more significant refactoring though.

**Comment by jpsim** [comment]
> Having a complex LD_RUNPATH_SEARCH_PATHS is a necessary evil, for now; I think the long-term solution is to find the toolchain at runtime rather than link-time, which I was working on in another branch. That'll require more significant refactoring though.

:+1:

**Comment by norio-nomura** [comment]
> Having a complex LD_RUNPATH_SEARCH_PATHS is a necessary evil, for now

I think we should avoid containing `/usr/lib` into LC_RPATH on .pkg and Homebrew installation.
I can't explain the reason for merging this PR with containing that.

>  I think the long-term solution is to find the toolchain at runtime rather than link-time

Agree. That will fix #160, #167.

**Comment by jpsim** [comment]
These changes look good, but it looks like @norio-nomura still has reservations. @norio-nomura & @zwaldowski  what do you think?

**Comment by norio-nomura** [comment]
I think:
- Changes in`sourcekitten.xcodeproj/project.pbxproj` about `LD_RUNPATH_SEARCH_PATHS ` can't be accepted. But those changes will be replaced by #176 if that will be merged.
- Changes in `Makefile` will needed to be rewritten when Xcode 7.3 will be released. After releasing of Xcode 7.3, I can't judge whether we should keep SourceKitten will be able to be built by using Xcode with swift-DEVELOPMENT-SNAPSHOT. Because I don't know whether swift-DEVELOPMENT-SNAPSHOT will maintain capability that building codes written for swift-2.x.
- Changes in `Source/SourceKittenFramework/SwiftDeclarationKind.swift`, `Source/SourceKittenFramework/Xcode.swift`and `Source/SourceKittenFrameworkTests/SourceKitTests.swift` would be needed to merge for reflecting changes of `FunctionOperator`.

**Comment by norio-nomura** [comment]
I confirmed that `swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a` can't build codes written for swift-2.x.

**Comment by jpsim** [comment]
I'm sorry I've done a terrible job at shepherding this PR through, despite your continued hard work @zwaldowski!

Now that #178 has landed, is there anything that we should still apply from this PR that isn't already handled?

**Comment by zwaldowski** [comment]
Should be fine.

**Pull request closed without merging**
