### PR TITLE
Enable `testParseFullXMLDocs()` on Linux

### PR DESCRIPTION
**Pull request by norio-nomura**

### CODE REVIEW

**Comment by jpsim** [comment]
Hurray!

**Comment by norio-nomura** [comment]
In Swift 3.1.1 for Linux, the test result can not be trusted because of #384.
Should we write `#if os(Linux) && !swift(>=3.2)` in the tests affected by #384?
Or can we end support to build with Swift 3.1.1?

**Comment by jpsim** [comment]
> Or can we end support to build with Swift 3.1.1?

Was thinking of doing this soon, which is why I just released 0.18.4.

**Comment by norio-nomura** [comment]
Ok. 👍

**Pull request merged**
