### PR TITLE
Add ability to create request from yaml

### PR DESCRIPTION
**Pull request by keith**
This allows consumers of SourceKittenFramework to pass a yaml formatted
string in order to create a sourcekit request.

Related: https://github.com/jpsim/SourceKitten/issues/312

### CODE REVIEW

**Comment by jpsim** [comment]
A tiny test for this would be 👌 💯

**Comment by keith** [comment]
Can do!

**Comment by keith** [comment]
Updated with a test. If you think this test should move somewhere else let me know, I wrestled with where to put it.

**Comment by jpsim** [comment]
> I wrestled with where to put it.

`SourceKitTests.swift` is the best place for it 👍. Add a changelog entry and :shipit:

**Comment by keith** [comment]
Added entry!

**Comment by jpsim** [comment]
Thanks @keith!

**Comment by jpsim** [comment]
Next up, you should expose this in the CLI 😉

**Comment by keith** [comment]
That is the plan! What do you think about either:

```
sourcekitten yaml --file foo.yml (or --text "yaml string")
```

Or maybe `yaml-request` instead of just `yaml`?

**Comment by jpsim** [comment]
I like `yaml-request`. Or `sourcekitten request --yaml [file or yaml string]`

**Comment by keith** [comment]
Submitted here: https://github.com/jpsim/SourceKitten/pull/315

**Pull request merged**
