### PR TITLE
Change `sourcekitd_*` functions to public

### LINKED ISSUE #487: Undefined symbol errors when creating a custom request.
Hey, I'm trying to create a custom request yet I'm getting undefined symbol errors for all of the sourcekitd functions. It looks like SourceKitten is [dynamically loading the framework](https://github.com/jpsim/SourceKitten/blob/cf04030867b7910658d23631da40df39cb609a65/Source/SourceKittenFramework/library_wrapper_sourcekitd.swift#L7). Do I need to duplicate this process, or does SourceKitten expose a helper of some kind?

I'm using SourceKitten via Carthage.

```swift
func requestSymbolSuperclasses(_ kind: SymbolKind, name: String, usr: String) -> [String: Any] {
    let symbolOptions = [
        sourcekitd_uid_get_from_cstr("key.indexer.arg.symbol.name")!: sourcekitd_request_string_create(name),
        sourcekitd_uid_get_from_cstr("key.indexer.arg.symbol.kind")!: sourcekitd_request_string_create(kind.rawValue),
        sourcekitd_uid_get_from_cstr("key.indexer.arg.symbol.language")!: sourcekitd_request_string_create("Xcode.SourceCodeLanguage.Swift"),
        sourcekitd_uid_get_from_cstr("key.indexer.arg.symbol.resolution")!: sourcekitd_request_string_create(usr)
    ]

    var symbolOptionsKeys = Array(symbolOptions.keys.map({ $0 as sourcekitd_uid_t? }))
    var symbolOptionsValues = Array(symbolOptions.values)

    let dict = [
        sourcekitd_uid_get_from_cstr("key.request")!: sourcekitd_request_uid_create(sourcekitd_uid_get_from_cstr(RequestKind.symbolSuperclasses.rawValue)!),
        sourcekitd_uid_get_from_cstr("key.symbol")!: sourcekitd_request_dictionary_create(&symbolOptionsKeys, &symbolOptionsValues, symbolOptions.count)
    ]

    var keys = Array(dict.keys.map({ $0 as sourcekitd_uid_t? }))
    var values = Array(dict.values)
    let response: [String: Any]

    do {
        response = try Request.customRequest(request: sourcekitd_request_dictionary_create(&keys, &values, dict.count)!).send()
    } catch {
        fatalError("Symbol superclasses request failed: \(error)")
    }

    return response
}
```

### PR DESCRIPTION
**Pull request by norio-nomura**
Fix #487

### CODE REVIEW

**Comment by norio-nomura** [comment]
Closing since #487 was closed.
I think that it is not good that there is no function to create `sourcekitd_object_t` which `Request.customRequest` needs.

**Comment by ileitch** [comment]
Oh, I thought this change was still valid. For example you can create a `sourcekitd_object_t` from `sourcekitd_request_dictionary_create`, e.g `Request.customRequest(request: sourcekitd_request_dictionary_create(&keys, &values, dict.count)!).send()`.

Without this PR it makes little sense for `customRequest` to be public, I don't see any other way to use it?

**Comment by norio-nomura** [comment]
Sorry, reopened.

**Comment by norio-nomura** [comment]
As a personal opinion, I would like to recommend #490 than this.

**Comment by jpsim** [comment]
Agreed, let's pursue #490 over this. Thanks for leading the charge, @norio-nomura.

**Pull request closed without merging**
