### PR TITLE
Add 'SWIFT_VERSION=3.0' to project file

### PR DESCRIPTION
**Pull request by S2dentik**
It doesn't build with Xcode 8.2 otherwise.

### CODE REVIEW

**Comment by norio-nomura** [comment]
Should we change them on project configuration instead of target configurations?

**Comment by jpsim** [comment]
☝️ what @norio-nomura said.

Thanks @S2dentik!

**Comment by S2dentik** [comment]
Yeah, that would make sense, tried that, but Xcode doesn't actually take into consideration those, nor are we able to specify `$(inherited)` for `SWIFT_VERSION` so adding it to project configuration doesn't fix the thing.

**Comment by S2dentik** [comment]
Another question would be, should we also change the `travis.yml`?

**Comment by norio-nomura** [comment]
Current project config already has `SWIFT_VERSION = 3.0.1`. We don't need `$(inherited)` on them.
> Another question would be, should we also change the `travis.yml`?

I have no objection to that.

**Comment by jpsim** [comment]
Closing since there's no need to do this given that the current project config already has `SWIFT_VERSION = 3.0.1` as @norio-nomura said. I'll change travis to test on Xcode 8.2 in an upcoming PR.

**Comment by S2dentik** [comment]
@jpsim This is an Xcode bug, and that's what this PR actually does, it fixes that.
http://stackoverflow.com/questions/41118912/use-legacy-swift-language-version-xcode-8-2
In the new version of Xcode you should basically select the `Use Legacy Swift version` to `No` again, and it does add this line to target. Without it, the target doesn't build.

**Comment by jpsim** [comment]
@S2dentik yeah, sorry I misunderstood, but fixing this at the project level is still better than at the framework level. See #317.

**Comment by S2dentik** [comment]
@jpsim Yeah, I guess changing it on the project level would be a better decision 👍 Totally agree

**Pull request closed without merging**
