### PR TITLE
support DOS newlines in NSString.lineAndCharacterForByteOffset(_:)

### PR DESCRIPTION
**Pull request by jpsim**
Fixes realm/SwiftLint#315 /cc @norio-nomura

### CODE REVIEW

**Comment by norio-nomura** [comment]
As I tested, CRLF line ending does not cause the issue.
0x1A on file ending? https://en.wikipedia.org/wiki/Control-Z

**Comment by norio-nomura** [comment]
I can't reproduce the issue.

**Comment by norio-nomura** [comment]
I got reproduce the issue.

**Comment by norio-nomura** [comment]
I think following would be better:
```diff
diff --git a/Source/SourceKittenFramework/String+SourceKitten.swift b/Source/SourceKittenFramework/String+SourceKitten.swift
index 7f9b007..e766b89 100644
--- a/Source/SourceKittenFramework/String+SourceKitten.swift
+++ b/Source/SourceKittenFramework/String+SourceKitten.swift
@@ -176,7 +176,7 @@ extension NSString {
                 if length == line.byteRange.length {
                     character = content.utf16.count
                 } else {
-                    let endIndex = content.utf8.startIndex.advancedBy(length)
+                    let endIndex = content.utf8.startIndex.advancedBy(length, limit: content.utf8.endIndex)
                         .samePositionIn(content.utf16) ?? content.utf16.endIndex
                     character = content.utf16.startIndex.distanceTo(endIndex)
                 }
```

**Comment by norio-nomura** [comment]
Maybe we should use `advancedBy(_:limit:)` on all collections that exposed by `String`.
```swift
var str = "Hello, playground"

let array = Array(str.characters)

func advancedByCountPlusOne<C: CollectionType>(collection: C) -> C.Index.Distance {
    return collection.startIndex.distanceTo(collection.startIndex.advancedBy(collection.count + 1))
}

advancedByCountPlusOne(str.unicodeScalars)  // 17
advancedByCountPlusOne(str.utf16 )          // 18
advancedByCountPlusOne(array)               // 18
advancedByCountPlusOne(ArraySlice(array))   // 18
advancedByCountPlusOne(str.characters)      // fatal error: can not increment endIndex
advancedByCountPlusOne(str.utf8)            // fatal error: Can't increment past endIndex of String.UTF8View
```

**Comment by jpsim** [comment]
Replaced by @norio-nomura's work in #182

**Pull request closed without merging**
