### PR TITLE
Tests: normalise the fixtures path for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Ensure that we normalise the path when we substitute the path into the results to properly remove the basename of the fixture.

### CODE REVIEW

**Comment by jpsim** [comment]
Approach looks ok, I'll merge when you fix the remaining issues causing tests to fail.

**Comment by compnerd** [comment]
@jpsim any idea why this would be failing?

**Comment by jpsim** [comment]
> any idea why this would be failing?

It's adding a trailing `/` on macOS/Linux which wasn't there before.

This fixes the macOS/Linux tests:

```swift
// Strip out fixtures directory since it's dependent on the test machine's setup
let escapedFixturesDirectory = URL(fileURLWithPath: rootDirectory)
    .standardizedFileURL
    .withUnsafeFileSystemRepresentation { String(cString: $0!) }
    .replacingOccurrences(of: #"\"#, with: #"\\"#)
    .replacingOccurrences(of: "/", with: #"\/"#)
let escapedJSONString = jsonString.replacingOccurrences(of: escapedFixturesDirectory, with: "")
```

Is it ok to have the Windows paths skip adding the trailing path separator?

**Comment by compnerd** [comment]
```
-  "Subscript.swift" : {
+  "\/Subscript.swift" : {
```

This diff makes me think that the trailing suffix is important?

**Comment by jpsim** [comment]
We can just do a separate codepath for Windows for the time being:

```swift
    // Strip out fixtures directory since it's dependent on the test machine's setup
#if os(Windows)
    let escapedFixturesDirectory = URL(fileURLWithPath: rootDirectory)
        .standardizedFileURL
        .withUnsafeFileSystemRepresentation { String(cString: $0!) }
        .replacingOccurrences(of: #"\"#, with: #"\\"#)
        .replacingOccurrences(of: "/", with: #"\/"#)
#else
    let escapedFixturesDirectory = rootDirectory.replacingOccurrences(of: "/", with: #"\/"#)
#endif
    let escapedJSONString = jsonString.replacingOccurrences(of: escapedFixturesDirectory, with: "")
```

Adjust that for whatever you need on the Windows side.

**Review by jpsim — APPROVED** [review]

**Pull request merged**
