### PR TITLE
Add support for static_assert declaration

### PR DESCRIPTION
**Pull request by jaquish**

### CODE REVIEW

**Comment by johnfairh** [comment]
Thanks for this -- could you please add a changelog entry, see [CONTRIBUTING.md](https://github.com/jpsim/SourceKitten/blob/master/CONTRIBUTING.md)?

**Comment by jaquish** [comment]
Thanks for the pointer @johnfairh. Updated.

**Comment by johnfairh** [comment]
Hi @jpsim does this look OK to squash + merge?  There are Bazel CI failures that I don't understand but must be unrelated?

**Review by jpsim — APPROVED** [review]
Thanks for the PR, yes the bezel failures are unrelated.

**Pull request merged**
