### PR TITLE
Reduce build time

### PR DESCRIPTION
**Pull request by norio-nomura**
- Add `display_compilation_time` target to `Makefile`
- Reduce build time of two functions
- Set `-Xfrontend -warn-long-function-bodies=200` to `OTHER_SWIFT_FLAGS`

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks! We should probably lower the threshold even more if we can things to be stable (100-150).

**Comment by norio-nomura** [comment]
I think [The failing test on SPM](https://travis-ci.org/jpsim/SourceKitten/jobs/180907909) is affected by version up of `Result` that updated from 3.0.0 to 3.1.0.
I'll push a PR fixing that.

**Comment by norio-nomura** [comment]
Oh, [test triggered by merge commit](https://travis-ci.org/jpsim/SourceKitten/jobs/180910543) succeeded…

**Comment by norio-nomura** [comment]
> Oh, test triggered by merge commit succeeded…

Sorry, I started this PR from old master. 🙇

**Pull request merged**
