### PR TITLE
Support Swift 2.3 on Xcode 8

### PR DESCRIPTION
**Pull request by norio-nomura**
For continuing development of SwiftLint on latest Xcode, we need Swift 2.3 compatibility until we will complete transition to Swift 3.

### CODE REVIEW

**Comment by norio-nomura** [comment]
I guess we should stop supporting Swift Package Manager on master branch until Linux support.

**Comment by jpsim** [comment]
Thanks for doing this @norio-nomura!

> I guess we should stop supporting Swift Package Manager on master branch until Linux support.

That's fine.

I'm not sure what's going on with this diff:
image

**Comment by norio-nomura** [comment]
I added Commandant-swift2.2.json. Both of Xcode 7.3.1 and 8 are supported by this PR because Xcode 8 is still in beta.

**Comment by jpsim** [comment]
Ah yes, thanks. Could you remove the SPM jobs from travis?

**Comment by norio-nomura** [comment]
Updated and test passed.

**Comment by jpsim** [comment]
👍 Thanks! 😄

**Comment by norio-nomura** [comment]
:pray:

**Comment by norio-nomura** [comment]
Did you change merging method?

**Comment by jpsim** [comment]
What do you mean?

**Comment by norio-nomura** [comment]
GUI of `git log --graph` in SourceTree:
screenshot 2016-08-24 09 30 59

It seems merge commit happened from single parent.

**Comment by jpsim** [comment]
All I did was press the green "Merge" button in GitHub's web UI. Maybe this is related to their recent-ish changes in https://github.com/blog/2141-squash-your-commits ?

**Comment by norio-nomura** [comment]
Oh, I didn't know.
If you intended, it's ok. 👌

**Pull request merged**
