### PR TITLE
Adds a Dangerfile to SourceKitten

### PR DESCRIPTION
**Pull request by orta**
This PR should fail, as you'll need to set up the access token as with Jazzy. 👍

### CODE REVIEW

**Comment by jpsim** [comment]
I've added an access token as described in [Danger docs](https://danger.systems/guides/getting_started.html#setting-up-an-access-token), but it seems the build is failing because rbenv isn't installed on Travis, rather using RVM.

**Comment by orta** [comment]
Cool, I've changed it 👍 looks like it's ruby 2.0 too, so double OK

**Comment by jpsim** [comment]
```
11 gems installed
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.3.2/lib/danger/danger_core/environment_manager.rb:31:in `initialize': Could not find a Request Source for Danger::Travis (RuntimeError)
CI: #<Danger::Travis:0x007fe6732b2af8 @repo_slug="jpsim/SourceKitten", @pull_request_id="247", @repo_url="https://github.com/jpsim/SourceKitten.git", @supported_request_sources=[Danger::RequestSources::GitHub]>
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.3.2/lib/danger/danger_core/executor.rb:30:in `new'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.3.2/lib/danger/danger_core/executor.rb:30:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.3.2/lib/danger/commands/runner.rb:56:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.3.2/bin/danger:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/danger:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/danger:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
The command "gem install danger --version '~> 3.0' && danger" failed and exited with 1 during .
```

**Comment by orta** [comment]
Interesting! https://github.com/danger/danger/issues/519 we should do a better error message here.

Anyway, I don't see the ENV VAR set up, could you have it on private?

screen shot 2016-09-20 at 17 15 11

**Comment by jpsim** [comment]
> could you have it on private?

I do, is that not supported?

**Comment by jpsim** [comment]
I've re-added the key, but checking the "show this in logs" switch

**Comment by orta** [comment]
It's a part of how Travis works, those ENV vars are only exposed to branch PRs, instead of fork PRs to ensure that the values aren't leaked

**Comment by jpsim** [comment]
> If you have an open source project, you should ensure "Display value in build log" enabled, so that PRs from forks work.

👍  I should have RTFM

**Comment by orta** [comment]
Eh, ain't nobody got time for that

**Comment by orta** [comment]
Just like I didn't have time to read my own references :D

**Comment by jpsim** [comment]
I'm assuming you're aware of the `undefined local variable or method `lines_of_code'` failure?

**Comment by orta** [comment]
alright, it good

**Comment by jpsim** [comment]
Thanks @orta!

**Pull request merged**
