### PR TITLE
Re-add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by jpsim**
Targets and depends on #264.

### CODE REVIEW

**Comment by jpsim** [comment]
This has been rebased on `master` after #273 was merged. Thoughts @norio-nomura?

**Comment by norio-nomura** [comment]
It may be ok if ci will pass. 👍

BTW, I feel "Squash and merge” or “Rebase and merge” are making hard to rebasing another working branches…

**Comment by jpsim** [comment]
> BTW, I feel "Squash and merge” or “Rebase and merge” are making hard to rebasing another working branches…

Yes, that may be what caused the issues with #273 😬. I've disabled the "Squash and merge" option, as I think that's what was causing issues. I think "Rebase and merge" should be fine.

**Comment by norio-nomura** [comment]
> I've disabled the "Squash and merge" option, as I think that's what was causing issues.

Thank you! 🙏

**Pull request merged**
