### PR TITLE
Stable Swift 2.3 support

### PR DESCRIPTION
**Pull request by ikesyo**
This should be required for Swift 2.3 support on SwiftLint (related to https://github.com/realm/SwiftLint/issues/815).

### CODE REVIEW

**Comment by ikesyo** [comment]
Unfortunately `YamlSwift` does not have a tagged release which supports Swift 2.3 and the latest 1.4.4 release is migrated to Swift 3.0: https://github.com/behrang/YamlSwift/pull/30 😞

**Comment by ikesyo** [comment]
`YamlSwift` is now updated to 1.5.0: https://github.com/behrang/YamlSwift/pull/32#issuecomment-247910417

**Comment by jpsim** [comment]
Thanks @ikesyo!

**Comment by jpsim** [comment]
I'll add a changelog entry to state that Swift 2.3 support was added.

**Comment by jpsim** [comment]
23f3d4f

**Comment by ikesyo** [comment]
Thanks too @jpsim and @norio-nomura!

**Pull request merged**
