### PR TITLE
Some method do not have fullXMLDocs, in this case we will trying to extract swiftDeclaration from annotatedDeclaration.

### PR DESCRIPTION
**Pull request by ainopara**
As mentioned in #376, `swiftDeclaration` sometimes return nil.

I think that is due to `key.doc.full_as_xml` is marked as optional in current [SourceKit protocol](https://github.com/apple/swift/blob/swift-DEVELOPMENT-SNAPSHOT-2017-05-15-a/tools/SourceKit/docs/Protocol.md#cursor-info).

`SWXMLHash` is updated becasue `recursiveText` property is first introduced in 3.1.0 version.

### CODE REVIEW

**Comment by norio-nomura** [comment]
I opened #383 to fixing build error in `VersionCommand.swift`.

**Comment by norio-nomura** [comment]
Restarted `JOB=Xcode` on travis since #383 has been merged.

**Comment by ainopara** [comment]
Rebased.

**Comment by jpsim** [comment]
Excellent. Thanks!

**Pull request merged**
