### PR TITLE
add NSString.lineAndCharacterForByteOffset

### PR DESCRIPTION
**Pull request by jpsim**

### CODE REVIEW

**Comment by norio-nomura** [comment]
:+1: 
We need more performance optimization.

**Comment by jpsim** [comment]
> We need more performance optimization.

True, but we may have to rethink the string cache altogether though. I think we may be able to combine some caching instead of essentially adding a 3rd cache set here.

**Comment by norio-nomura** [comment]
I think converting all byte offset into utf16 index before passing models to client (SwiftLint).
Caching may not be needed by that.

**Comment by norio-nomura** [comment]
I have a small-scale implementation idea that extends current implementation.
I'll write that.

**Pull request merged**
