### PR TITLE
Update SWXMLHash to 4.9.0 to support Xcode 10.2

### PR DESCRIPTION
**Pull request by neakor**
This is an upstream requirement for https://github.com/uber/needle/issues/283

### CODE REVIEW

**Comment by neakor** [comment]
@jpsim can you please review this?

**Comment by jpsim** [comment]
👍 I think this is ok, despite that the Cartfile and git submodule still point to 4.8.0, because SWXMLHash 4.9.0 sets its Xcode project's `SWIFT_VERSION` to Swift 5, which breaks our compatibility with Xcode 10.0. However, that's less of a concern for `Package.swift`.

**Comment by jpsim** [comment]
Do you need me to cut a new SourceKitten release to use this?

**Comment by neakor** [comment]
@jpsim yes please. Can you make a new release please?

**Comment by jpsim** [comment]
Already released 0.23.1: https://github.com/jpsim/SourceKitten/releases/tag/0.23.1

**Comment by neakor** [comment]
Awesome! Thanks much!

**Pull request merged**
